### PR TITLE
Update lightbulb.py

### PR DESCRIPTION
**Pull request by vt-d**

### CODE REVIEW

**Comment by MPlatypus** [comment]
Hi, can I ask why this pr has been made?

**Comment by vt-d** [comment]
> Hi, can I ask why this pr has been made?

Hey @MPlatypus Lightbulb usually does not capture the whole query and takes certain chunks of it based on spacing. This fixes that by consuming the rest of the message. i.e. in `~play Yasuha - Flyday Chinatown` the rest of the string, excluding `~play ` is taken. (Yasuha - Flyday Chinatown)

**Comment by MPlatypus** [comment]
That is true, However, my implementation in the examples only supports slash commands, as I did not setup prefix commands.

Slash commands do not use the consume method. 

If you use prefix commands with the example, It should not work, unless modified to support things like the consume method.

However, now that you have brought this to my attention, when I release the new version of Ongaku, I can rebuild the examples to support both prefix and slash commands.

**Comment by vt-d** [comment]
Alright, I understand. I will now close this issue.

**Pull request closed without merging**
